# Generated by Django 6.0.3 on 2026-03-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JewelryCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('item_type', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('material', models.CharField(max_length=100)),
                ('occasion', models.CharField(max_length=100)),
                ('aesthetic', models.CharField(max_length=100)),
                ('price_range', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('product_link', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'jewelry_catalog',
            },
        ),
        migrations.RenameField(
            model_name='preferenceresult',
            old_name='agreeableness_score',
            new_name='aesthetic_score',
        ),
        migrations.RenameField(
            model_name='preferenceresult',
            old_name='conscientiousness_score',
            new_name='budget_score',
        ),
        migrations.RenameField(
            model_name='preferenceresult',
            old_name='extraversion_score',
            new_name='material_score',
        ),
        migrations.RenameField(
            model_name='preferenceresult',
            old_name='neuroticism_score',
            new_name='occasion_score',
        ),
        migrations.RenameField(
            model_name='preferenceresult',
            old_name='openness_score',
            new_name='style_score',
        ),
        migrations.AddField(
            model_name='preferenceresult',
            name='jewelry_persona',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='category',
            field=models.CharField(choices=[('Style', 'Style Preference'), ('Material', 'Material Preference'), ('Occasion', 'Occasion Type'), ('Aesthetic', 'Design Aesthetic'), ('Budget', 'Budget Range')], max_length=30),
        ),
    ]
