# Generated by Django 6.0.3 on 2026-03-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference_app', '0002_jewelrycatalog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelrycatalog',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jewelrycatalog',
            name='material',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jewelrycatalog',
            name='occasion',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jewelrycatalog',
            name='price_range',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='jewelrycatalog',
            name='style',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
