# Generated by Django 6.0.3 on 2026-03-13 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference_app', '0003_jewelrycatalog_price_alter_jewelrycatalog_material_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jewelrycatalog',
            name='visual_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SwipeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'swipe_sessions',
            },
        ),
        migrations.CreateModel(
            name='SwipeResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preference_app.jewelrycatalog')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='preference_app.swipesession')),
            ],
            options={
                'db_table': 'swipe_responses',
            },
        ),
    ]
