# Generated by Django 6.0.3 on 2026-03-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference_app', '0006_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenceresult',
            name='metal_preference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='preferenceresult',
            name='stone_preference',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='preferenceresult',
            name='style_aesthetic',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
