# Generated by Django 6.0.3 on 2026-04-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference_app', '0010_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
